### ISSUE TITLE
Petting your Fears Application

### ISSUE THREAD

**Issue by irvinmdoza** [BYUCS452F2021/pet-your-fears#1]
Hello!
My name is Irvin Mendoza and I am interesting in helping develop this application. I admittedly know very little about phobias but I think that I have some skills, both technical and visual, that can help with the development of the system you described!  I have real world experience in both front and back end development, as well as skills in digital art that could be useful in the use of gradual exposure therapy, which is what I believe the intended goal of this system.  I would like to know a little more about how the system you have in mind works, but I think that can be fleshed out as a team once there is a more defined set of team members. Thank you!

**Comment by irvinmdoza** [comment]
I've been asked to join another team; I can no longer commit to this project.

**Comment by mikaylacheng** [comment]
So sorry I just saw your comment Irvin! Your skills are amazing and would have been really useful for the project! Good luck with you new team!
